// <auto-generated />
namespace JohannasApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedrequiredExpCat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedrequiredExpCat));
        
        string IMigrationMetadata.Id
        {
            get { return "202102120910535_Added required ExpCat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
